In [1]:
import numpy as np
from FeatExtract import get_bvp_features


In [2]:
expressive = [
1,
21,
25,
26,
27,
32,
33,
37,
39,
41,
45,
47,
49,
51,
53,
54,
56,
57,
58,
61
]

In [3]:
results = []

In [4]:
window_size = 8
BVPs = get_bvp_features(window_size)

Skipping Patient_2, Q1_1
Skipping Patient_52, Q7_2
Loaded 478 BVP signals
Failed: Patient_14, Q1_2atient_14...
Extracted features for 476 videos...
[('mean_hr_mean', np.float64(93.77445719665997)), ('mean_hr_std', np.float64(10.011686172939756)), ('mean_hr_range', np.float64(23.724105721949925)), ('hr_slope_mean', np.float64(-1.8572434075468458)), ('hr_slope_std', np.float64(1.656103154491383)), ('hr_slope_range', np.float64(4.02516601748533)), ('rmssd_mean', np.float64(0.19855451126646115)), ('rmssd_std', np.float64(0.046700650953390155)), ('rmssd_range', np.float64(0.11432843994570391)), ('ibi_cv_mean', np.float64(0.25539819459387814)), ('ibi_cv_std', np.float64(0.0730932757305431)), ('ibi_cv_range', np.float64(0.15875141138172472)), ('dom_freq_mean', np.float64(1.1952941176470586)), ('dom_freq_std', np.float64(0.06798575059331934)), ('dom_freq_range', np.float64(0.16517647058823526)), ('peak_power_ratio_mean', np.float64(0.05138165323282271)), ('peak_power_ratio_std', np.float64(0.0

In [5]:
print("Example of features: ", BVPs[0].features.keys())
print("Features per video: ", len(BVPs[0].features))

Example of features:  dict_keys(['mean_hr_mean', 'mean_hr_std', 'mean_hr_range', 'hr_slope_mean', 'hr_slope_std', 'hr_slope_range', 'rmssd_mean', 'rmssd_std', 'rmssd_range', 'ibi_cv_mean', 'ibi_cv_std', 'ibi_cv_range', 'dom_freq_mean', 'dom_freq_std', 'dom_freq_range', 'peak_power_ratio_mean', 'peak_power_ratio_std', 'peak_power_ratio_range', 'spec_entropy_mean', 'spec_entropy_std', 'spec_entropy_range', 'freq_variance_mean', 'freq_variance_std', 'freq_variance_range', 'hr_snr_mean', 'hr_snr_std', 'hr_snr_range', 'amp_mean_mean', 'amp_mean_std', 'amp_mean_range', 'amp_std_mean', 'amp_std_std', 'amp_std_range', 'sample_entropy_mean', 'sample_entropy_std', 'sample_entropy_range', 'perm_entropy_mean', 'perm_entropy_std', 'perm_entropy_range', 'peak_success_ratio_mean', 'peak_success_ratio_std', 'peak_success_ratio_range'])
Features per video:  42


In [6]:
label_map = {
    "Q1": "Q1: ↑Arousal ↓Val",
    "Q2": "Q2: ↑Arousal -Val",
    "Q3": "Q3: ↑Arousal ↑Val",
    "Q4": "Q4: -Arousal ↓Val",
    "Q5": "Q5: -Arousal -Val",
    "Q6": "Q6: -Arousal ↑Val",
    "Q7": "Q7: ↓Arousal ↓Val",
    "Q8": "Q8: ↓Arousal -Val",
    "Q9": "Q9: ↓Arousal ↑Val",
}

def get_label(path):
    q = path.split("_")[0]  # "Q3_2" → "Q3"
    return label_map[q]



In [7]:
for bvp in BVPs:

    try: 

        for feat, val in bvp.features.items():
            #print(feat, val)
            i = 1
        #print(bvp.patient, bvp.path, "Success")

    except Exception as e:
        print(bvp.patient, bvp.path, e)


14 Q3_1 'list' object has no attribute 'items'


In [8]:
import numpy as np

X = []
y = []

for bvp in BVPs:
    if bvp is None or bvp.features == []:
        print("Error: Patient", bvp.patient, bvp.path)
        continue

    feat_values = list(bvp.features.values())
    X.append(feat_values)
    y.append(get_label(bvp.path))
    

X = np.array(X)
y = np.array(y)

print(X.shape, y.shape)
print(np.unique(y, return_counts=True))
print("Example of data: ", X[0])


Error: Patient 14 Q3_1
(476, 42) (476,)
(array(['Q1: ↑Arousal ↓Val', 'Q3: ↑Arousal ↑Val', 'Q7: ↓Arousal ↓Val',
       'Q9: ↓Arousal ↑Val'], dtype='<U17'), array([118, 119, 119, 120]))
Example of data:  [ 9.37744572e+01  1.00116862e+01  2.37241057e+01 -1.85724341e+00
  1.65610315e+00  4.02516602e+00  1.98554511e-01  4.67006510e-02
  1.14328440e-01  2.55398195e-01  7.30932757e-02  1.58751411e-01
  1.19529412e+00  6.79857506e-02  1.65176471e-01  5.13816532e-02
  4.36826439e-03  1.03046325e-02  5.99903188e+00  1.41085362e-01
  3.45538352e-01  2.06318138e-01  9.68606097e-02  2.14143685e-01
  1.31537032e+01  1.11827568e+00  2.63798592e+00  2.36025784e-01
  6.21272006e-03  1.50620738e-02  1.16054104e-01  1.92745995e-02
  4.61180999e-02  4.52405534e-01  3.80627462e-02  8.76340457e-02
  1.46169091e+00  1.84037102e-02  4.36432806e-02  9.63693781e-01
  3.99997249e-02  9.03327078e-02]


LEARNING

In [9]:
# # Random Split

# type = "Random"

# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y,
#     test_size=0.3,
#     stratify=y,      # important for emotions
#     random_state=42
# )

# print(X_train.shape, y_train.shape)
# print(X_test.shape, y_test.shape)

# print("Example of data: ", X_train[0])


In [10]:
# Expressive for test

type = "Expressive"


X_train = []
y_train = []

X_test = []
y_test = []

for bvp in BVPs:
    if bvp is None or bvp.features == []:
        print("Fatal Error: Patient", bvp.patient, bvp.path)
        continue

    elif bvp.patient in expressive:
        #print(bvp.patient, bvp.path, "EXPRESSIVE")
        X_train.append(list(bvp.features.values()))
        y_train.append(get_label(bvp.path))

    else:
        #print(bvp.patient, bvp.path, bvp.features, "REST")
        X_test.append(list(bvp.features.values()))
        y_test.append(get_label(bvp.path))

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)


print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

print("Example of data: ", X_train[0])

Fatal Error: Patient 14 Q3_1
(160, 42) (160,)
(316, 42) (316,)
Example of data:  [ 9.37744572e+01  1.00116862e+01  2.37241057e+01 -1.85724341e+00
  1.65610315e+00  4.02516602e+00  1.98554511e-01  4.67006510e-02
  1.14328440e-01  2.55398195e-01  7.30932757e-02  1.58751411e-01
  1.19529412e+00  6.79857506e-02  1.65176471e-01  5.13816532e-02
  4.36826439e-03  1.03046325e-02  5.99903188e+00  1.41085362e-01
  3.45538352e-01  2.06318138e-01  9.68606097e-02  2.14143685e-01
  1.31537032e+01  1.11827568e+00  2.63798592e+00  2.36025784e-01
  6.21272006e-03  1.50620738e-02  1.16054104e-01  1.92745995e-02
  4.61180999e-02  4.52405534e-01  3.80627462e-02  8.76340457e-02
  1.46169091e+00  1.84037102e-02  4.36432806e-02  9.63693781e-01
  3.99997249e-02  9.03327078e-02]


In [11]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test  = scaler.transform(X_test)


In [12]:
# from sklearn.linear_model import LogisticRegression

# clf = LogisticRegression(
#     max_iter=1000,
#     class_weight="balanced"  # helpful for imbalance
# )

# clf.fit(X_train, y_train)


In [13]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])



In [14]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

X = []
y = []
groups = []

for bvp in BVPs:
    if bvp is None or bvp.features == []:
        print(f"Skipping Patient_{bvp.patient} {bvp.path}")
        continue

    X.append(list(bvp.features.values()))
    y.append(get_label(bvp.path))
    groups.append(bvp.patient)

X = np.array(X)
y = np.array(y)
groups = np.array(groups)

Skipping Patient_14 Q3_1


In [15]:
from sklearn.model_selection import StratifiedGroupKFold, cross_val_score

cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    pipe,
    X,
    y,
    groups=groups,
    cv=cv,
    scoring="f1_macro"
)

print("F1 macro:", scores.mean(), "±", scores.std())


F1 macro: 0.40245885935874115 ± 0.04230041652430009


In [16]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = pipe.predict(X_test)

clasif_report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

results.append([pipe, clasif_report, conf_matrix, type, window_size])

print(clasif_report)
print(conf_matrix)


                   precision    recall  f1-score   support

Q1: ↑Arousal ↓Val       0.37      0.40      0.39        78
Q3: ↑Arousal ↑Val       0.38      0.20      0.26        79
Q7: ↓Arousal ↓Val       0.43      0.51      0.47        79
Q9: ↓Arousal ↑Val       0.35      0.44      0.39        80

         accuracy                           0.39       316
        macro avg       0.39      0.39      0.38       316
     weighted avg       0.39      0.39      0.38       316

[[31  6 13 28]
 [22 16 28 13]
 [ 9  7 40 23]
 [21 13 11 35]]


In [18]:
import pandas as pd

# feature names from BVP objects (windowed)
feature_names = list(BVPs[0].features.keys())

# extract RF importances from pipeline
importances = pipe.named_steps['clf'].feature_importances_

# build DataFrame
imp_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

print(imp_df)


                     feature  importance
38        perm_entropy_range    0.050692
35      sample_entropy_range    0.036352
29            amp_mean_range    0.035633
28              amp_mean_std    0.031774
14            dom_freq_range    0.030677
3              hr_slope_mean    0.028659
5             hr_slope_range    0.028188
24               hr_snr_mean    0.028125
34        sample_entropy_std    0.027858
37          perm_entropy_std    0.027682
20        spec_entropy_range    0.026396
19          spec_entropy_std    0.026102
32             amp_std_range    0.025937
41  peak_success_ratio_range    0.025309
18         spec_entropy_mean    0.025292
23       freq_variance_range    0.024630
40    peak_success_ratio_std    0.024526
11              ibi_cv_range    0.024188
26              hr_snr_range    0.023635
15     peak_power_ratio_mean    0.022777
13              dom_freq_std    0.022664
4               hr_slope_std    0.022557
39   peak_success_ratio_mean    0.022359
8               

In [19]:
for result in results:
    print("-"*60)
    print(f"{result[3]}, Window Size: {result[4]}")
    print(result[1])
    print(result[2])
    print()

------------------------------------------------------------
Expressive, Window Size: 8
                   precision    recall  f1-score   support

Q1: ↑Arousal ↓Val       0.37      0.40      0.39        78
Q3: ↑Arousal ↑Val       0.38      0.20      0.26        79
Q7: ↓Arousal ↓Val       0.43      0.51      0.47        79
Q9: ↓Arousal ↑Val       0.35      0.44      0.39        80

         accuracy                           0.39       316
        macro avg       0.39      0.39      0.38       316
     weighted avg       0.39      0.39      0.38       316

[[31  6 13 28]
 [22 16 28 13]
 [ 9  7 40 23]
 [21 13 11 35]]

