In [ ]:
# bvp = list(range(1, 11))
# win_len = 3

# windows = []

# # Regular windows
# for start in range(0, len(bvp) - win_len + 1, win_len):
#     windows.append(bvp[start:start + win_len])

# # Force final window (end-aligned)
# end_start = len(bvp) - win_len
# if end_start > 0 and end_start not in range(0, len(bvp) - win_len + 1, win_len):
#     windows.append(bvp[end_start:end_start + win_len])

# for win in windows:
#     print(win)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[8, 9, 10]


In [ ]:
import numpy as np
from FeatExtract_CUT import get_bvp_features


In [2]:
results = []

In [3]:
quadrants_all = [
    "Q1_1",
    "Q1_2",
    "Q2_1",
    "Q2_2",
    "Q3_1",
    "Q3_2",
    "Q4_1",
    "Q4_2",
    "Q5_1",
    "Q5_2",
    "Q6_1",
    "Q6_2",
    "Q7_1",
    "Q7_2",
    "Q8_1",
    "Q8_2",
    "Q9_1",
    "Q9_2"
]

quadrants_arousal = [
    "Q1_1",
    "Q1_2",
    "Q2_1",
    "Q2_2",
    "Q3_1",
    "Q3_2",
    "Q7_1",
    "Q7_2",
    "Q8_1",
    "Q8_2",
    "Q9_1",
    "Q9_2"
]

quadrants_valence = [
    "Q1_1",
    "Q1_2",
    "Q3_1",
    "Q3_2",
    "Q4_1",
    "Q4_2",
    "Q6_1",
    "Q6_2",
    "Q7_1",
    "Q7_2",
    "Q9_1",
    "Q9_2"
]

quadrants_5q = [
    "Q1_1",
    "Q1_2",
    "Q3_1",
    "Q3_2",
    "Q5_1",
    "Q5_2",
    "Q7_1",
    "Q7_2",
    "Q9_1",
    "Q9_2"
]


quadrants_4q = [
    "Q1_1",
    "Q1_2",
    "Q3_1",
    "Q3_2",
    "Q7_1",
    "Q7_2",
    "Q9_1",
    "Q9_2"
]

In [101]:
window_size = 8
full_vid_size = 20

BVPs = get_bvp_features(quadrants_4q, full_vid_size, window_length=window_size)

Skipping Patient_2, Q1_1
Skipping Patient_52, Q7_2
Loaded 478 BVP signals
Failed: Patient_14, Q1_2atient_14...
Extracted features for 476 videos...
[('mean_hr_mean', 94.71618182751081), ('mean_hr_std', 7.0479789056435935), ('mean_hr_range', 15.380297393191455), ('hr_slope_mean', -0.7588574577421167), ('hr_slope_std', 2.4931819722455026), ('hr_slope_range', 6.055373243499959), ('rmssd_mean', 0.2124491200911889), ('rmssd_std', 0.05511063483637317), ('rmssd_range', 0.13469070000780453), ('ibi_cv_mean', 0.2599344101179731), ('ibi_cv_std', 0.04829235462628949), ('ibi_cv_range', 0.11825167584805446), ('dom_freq_mean', 1.2014117647058822), ('dom_freq_std', 0.05851873978969802), ('dom_freq_range', 0.1284705882352939), ('peak_power_ratio_mean', 0.04770818422933373), ('peak_power_ratio_std', 0.005506665339497426), ('peak_power_ratio_range', 0.013438510761067973), ('spec_entropy_mean', 6.155459418882869), ('spec_entropy_std', 0.20044638024053432), ('spec_entropy_range', 0.4343174330995314), ('fre

In [102]:
print("Example of features: ", BVPs[0].features.keys())
print("Features per video: ", len(BVPs[0].features))

Example of features:  dict_keys(['mean_hr_mean', 'mean_hr_std', 'mean_hr_range', 'hr_slope_mean', 'hr_slope_std', 'hr_slope_range', 'rmssd_mean', 'rmssd_std', 'rmssd_range', 'ibi_cv_mean', 'ibi_cv_std', 'ibi_cv_range', 'dom_freq_mean', 'dom_freq_std', 'dom_freq_range', 'peak_power_ratio_mean', 'peak_power_ratio_std', 'peak_power_ratio_range', 'spec_entropy_mean', 'spec_entropy_std', 'spec_entropy_range', 'freq_variance_mean', 'freq_variance_std', 'freq_variance_range', 'hr_snr_mean', 'hr_snr_std', 'hr_snr_range', 'amp_mean_mean', 'amp_mean_std', 'amp_mean_range', 'amp_std_mean', 'amp_std_std', 'amp_std_range', 'sample_entropy_mean', 'sample_entropy_std', 'sample_entropy_range', 'perm_entropy_mean', 'perm_entropy_std', 'perm_entropy_range', 'peak_success_ratio_mean', 'peak_success_ratio_std', 'peak_success_ratio_range'])
Features per video:  42


In [103]:
label_map = {
    "Q1": "Q1: ↑Arousal ↓Val",
    "Q2": "Q2: ↑Arousal -Val",
    "Q3": "Q3: ↑Arousal ↑Val",
    "Q4": "Q4: -Arousal ↓Val",
    "Q5": "Q5: -Arousal -Val",
    "Q6": "Q6: -Arousal ↑Val",
    "Q7": "Q7: ↓Arousal ↓Val",
    "Q8": "Q8: ↓Arousal -Val",
    "Q9": "Q9: ↓Arousal ↑Val",
}

def get_label(quadrant):
    q = quadrant.split("_")[0]  # "Q3_2" → "Q3"
    return label_map[q]



In [104]:
for bvp in BVPs:

    try: 

        for feat, val in bvp.features.items():
            #print(feat, val)
            i = 1
        #print(bvp.patient, bvp.quadrant, "Success")

    except Exception as e:
        print(bvp.patient, bvp.quadrant, e)


14 Q3_1 'list' object has no attribute 'items'


In [105]:
import numpy as np

X = []
y = []

for bvp in BVPs:
    if bvp is None or bvp.features == []:
        print("Error: Patient", bvp.patient, bvp.quadrant)
        continue

    feat_values = list(bvp.features.values())
    X.append(feat_values)
    y.append(get_label(bvp.quadrant))
    

X = np.array(X)
y = np.array(y)

print(X.shape, y.shape)
print(np.unique(y, return_counts=True))
print("Example of data: ", X[0])


Error: Patient 14 Q3_1
(476, 42) (476,)
(array(['Q1: ↑Arousal ↓Val', 'Q3: ↑Arousal ↑Val', 'Q7: ↓Arousal ↓Val',
       'Q9: ↓Arousal ↑Val'], dtype='<U17'), array([118, 119, 119, 120], dtype=int64))
Example of data:  [ 9.47161818e+01  7.04797891e+00  1.53802974e+01 -7.58857458e-01
  2.49318197e+00  6.05537324e+00  2.12449120e-01  5.51106348e-02
  1.34690700e-01  2.59934410e-01  4.82923546e-02  1.18251676e-01
  1.20141176e+00  5.85187398e-02  1.28470588e-01  4.77081842e-02
  5.50666534e-03  1.34385108e-02  6.15545942e+00  2.00446380e-01
  4.34317433e-01  2.00839879e-01  5.32852018e-02  1.27464578e-01
  1.22132952e+01  1.40970633e+00  3.44025875e+00  2.36298543e-01
  1.09980205e-02  2.67701966e-02  1.35353629e-01  1.38621402e-02
  3.19251612e-02  4.84533391e-01  3.15613452e-02  6.82113217e-02
  1.45739788e+00  2.34862855e-02  5.74880702e-02  9.27236700e-01
  5.64107940e-02  1.38060966e-01]


LEARNING

In [106]:
# Random Split

type = "Random"

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,      # important for emotions
    random_state=42
)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

print("Example of data: ", X_train[0])


(333, 42) (333,)
(143, 42) (143,)
Example of data:  [1.01192242e+02 3.37822442e+00 7.98933676e+00 5.33110150e-01
 5.50191093e-01 1.32679565e+00 8.57295727e-02 1.50398786e-02
 3.65073341e-02 8.94091275e-02 1.90949489e-02 4.47626149e-02
 1.68164706e+00 5.62357864e-02 1.37647059e-01 4.68505928e-02
 3.41896791e-03 8.37328072e-03 6.26071162e+00 1.71252228e-01
 4.19480459e-01 1.24018445e-01 2.93047658e-02 6.80337071e-02
 1.19937518e+01 8.75255785e-01 2.14355986e+00 1.88428964e-01
 3.52207237e-02 8.47055682e-02 5.72898071e-02 6.95082611e-03
 1.52637287e-02 5.35576431e-01 1.99686043e-02 4.31384920e-02
 1.54467187e+00 7.74808164e-02 1.83116756e-01 9.88514932e-01
 2.60490583e-02 5.77649413e-02]


In [107]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])



In [108]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

X = []
y = []
groups = []

for bvp in BVPs:
    if bvp is None or bvp.features == []:
        print(f"Skipping Patient_{bvp.patient} {bvp.quadrant}")
        continue

    X.append(list(bvp.features.values()))
    y.append(get_label(bvp.quadrant))
    groups.append(bvp.patient)

X = np.array(X)
y = np.array(y)
groups = np.array(groups)

Skipping Patient_14 Q3_1


In [109]:
from sklearn.model_selection import StratifiedGroupKFold, cross_val_score

cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    pipe,
    X,
    y,
    groups=groups,
    cv=cv,
    scoring="f1_macro"
)

print("F1 macro:", scores.mean(), "±", scores.std())

results.append([full_vid_size, window_size, scores.mean(), scores.std()])


F1 macro: 0.30093979410183924 ± 0.011242569677144773


In [110]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [111]:
import joblib

joblib.dump(pipe, "bvp_emotion_pipeline.joblib")

# import joblib

# pipe = joblib.load("bvp_emotion_pipeline.joblib")

# pipe.predict(X)
# pipe.predict_proba(X)
# pipe.classes_

['bvp_emotion_pipeline.joblib']

In [112]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = pipe.predict(X_test)

clasif_report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

#results.append([pipe, clasif_report, conf_matrix, type, window_size])

print(clasif_report)
print(conf_matrix)


                   precision    recall  f1-score   support

Q1: ↑Arousal ↓Val       0.19      0.17      0.18        35
Q3: ↑Arousal ↑Val       0.24      0.19      0.22        36
Q7: ↓Arousal ↓Val       0.26      0.25      0.26        36
Q9: ↓Arousal ↑Val       0.22      0.31      0.26        36

         accuracy                           0.23       143
        macro avg       0.23      0.23      0.23       143
     weighted avg       0.23      0.23      0.23       143

[[ 6 13  5 11]
 [ 7  7  9 13]
 [ 8  5  9 14]
 [10  4 11 11]]


In [113]:
import pandas as pd

# feature names from BVP objects (windowed)
feature_names = list(BVPs[0].features.keys())

# extract RF importances from pipeline
importances = pipe.named_steps['clf'].feature_importances_

# build DataFrame
imp_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

print(imp_df)


                     feature  importance
28              amp_mean_std    0.029266
38        perm_entropy_range    0.029164
29            amp_mean_range    0.028007
10                ibi_cv_std    0.027925
11              ibi_cv_range    0.027776
23       freq_variance_range    0.027525
22         freq_variance_std    0.027241
24               hr_snr_mean    0.026471
3              hr_slope_mean    0.025985
4               hr_slope_std    0.025916
21        freq_variance_mean    0.025808
0               mean_hr_mean    0.025713
35      sample_entropy_range    0.025168
33       sample_entropy_mean    0.025014
18         spec_entropy_mean    0.024829
19          spec_entropy_std    0.024564
2              mean_hr_range    0.024380
15     peak_power_ratio_mean    0.024270
8                rmssd_range    0.024122
40    peak_success_ratio_std    0.023770
5             hr_slope_range    0.023691
41  peak_success_ratio_range    0.023634
37          perm_entropy_std    0.023536
34        sample

In [114]:
print("Full Video Size                      Window Size                                 F1 Value")
print()

for result in results:
    print(f"     {result[0]}                                  {result[1]}                                   {result[2]:.4f}  ± {result[3]:.4f}")
    print()

Full Video Size                      Window Size                                 F1 Value

     200                                  8                                   0.4025  ± 0.0423

     18                                  6                                   0.2733  ± 0.0178

     30                                  8                                   0.3171  ± 0.0515

     30                                  6                                   0.3016  ± 0.0310

     50                                  8                                   0.3843  ± 0.0152

     20                                  8                                   0.3009  ± 0.0112

